---
title: "Meta-analysis of age-specific prevalence of Parkinson's disease"
output: html_document
date: "2023-06-22"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## open and process data

Open libraries

```{r libraries}
library(here)
library(meta)
library(readxl)
library(tidyverse)
```

Open data

```{r open-data}
data = read_excel("C:/Users/k2258693/OneDrive - King's College London/Desktop/PINNACLE project/5 Paper Systematic review PD prevalence/Data extraction table COMBINED_agespecific.xlsx")
```

Process data

```{r}
# Subset data
data = data[, 1:30]

# Rename variables
colnames(data) = c("studyid", "author", "year", "study_type", "meanage", "minage", "sexpct", "country", "urbanrural", "subgroup", "subgroup_level", "subgroup_age10", "subgroup_age60", "size", "n_pd", "N_pd", "PD_n_age10", "PD_N_age10", "PD_n_age60", "PD_N_age60", "pct_pd", "prev_pd", "n_pnism", "N_pnism", "pnism_n_age10", "pnism_N_age10", "pnism_n_age60", "pnism_N_age60", "pct_pnism", "prev_pnism")

# Remove first row
data = data[-1, ]

# Select relevant variables
data = data %>% 
  select(studyid, author, year, study_type, country, urbanrural, starts_with("subgroup"), ends_with("pd"), starts_with("PD"), ends_with("pnism"), starts_with("pnism"))

# Relabel 'Door-to-door' studies as 'Cohort study'
data = data %>% 
  mutate(study_type = factor(case_when(study_type == "Door-to-door" ~ "Cohort study", 
                                       study_type == "Adminstrative" ~ "Administrative",
                                       TRUE ~ study_type),
                             levels = c("Cohort study", "Administrative")))

# Exclude certain data from the 10/66 study - specifically, the rural and urban data from Peru and Mexico (these have been combined)
data = data %>% 
  filter(!(author=="Llibre-Guerra" & (country=="Peru" | country=="Mexico") & (urbanrural=="Urban" | urbanrural=="Rural")))
```

Create separate dataframes for age-specific analysis

```{r}
# Dataframe for age-specific prevalence by decade of age
data10 = data %>% 
  filter(!is.na(subgroup_age10)) %>% 
  mutate(study = paste0(author, ", ", year, " (", country, ")"), # create new study variables
         agegroup = factor(subgroup_age10, levels=c("40-49", "50-59", "60-69", "70-79", "\u226580"))) %>% 
  select(study, study_type, agegroup, ends_with("age10"), - subgroup_age10)%>% 
  mutate(across(ends_with("10"), as.integer))
  
# Dataframe for age-specific prevalence for >=60
data60 = data %>% 
  filter(!is.na(subgroup_age60)) %>% 
  mutate(study = paste0(author, ", ", year, " (", country, ")")) %>% # create new study variables
  select(study, study_type, ends_with("age60"), -subgroup_age60) %>% 
  mutate(across(ends_with("60"), as.integer))
```


## Meta-analysis and forest plots

### Prevalence

#### Parkinson's disease in >=60 year olds

```{r}
results_pd_age60 = data60 %>% 
  select(-starts_with("pnism")) %>% 
  drop_na() %>% 
  mutate(prev = PD_n_age60/PD_N_age60*100000) %>% 
  arrange(desc(prev))
  #arrange(country)

meta.output = meta::metaprop(event = PD_n_age60, 
                         n = PD_N_age60, 
                         studlab = study, 
                         pscale=100000, 
                         data = results_pd_age60, 
                         subgroup=study_type, 
                         common=FALSE,
                         random=TRUE,  
                         subgroup.name = "Study type")

summary(meta.output)
```

```{r}
png("age60_pd_prev_plot.png", width = 30, height = 20, units = "cm", res=500)

forest(meta.output, digits=0, digits.se=0)

dev.off()
```
#### Parkinsonism in >=60 year olds

```{r}
results_pnism_age60 = data60 %>% 
  select(-starts_with("PD")) %>% 
  drop_na() %>% 
  mutate(prev = pnism_n_age60/pnism_N_age60*100000) %>% 
  arrange(desc(prev))
  #arrange(country)

meta.output = meta::metaprop(event = pnism_n_age60, 
                         n = pnism_N_age60, 
                         studlab = study, 
                         pscale=100000, 
                         data = results_pnism_age60, 
                         subgroup=study_type, 
                         common=FALSE,
                         random=TRUE,  
                         subgroup.name = "Study type")

summary(meta.output)

png("age60_pnism_prev_plot.png", width = 30, height = 20, units = "cm", res=500)

forest(meta.output, digits=0, digits.se=0)

dev.off()
```

#### PD by age group

```{r}
results_pd_age10 = data10 %>% 
  select(-starts_with("pnism")) %>% 
  drop_na() %>% 
  mutate(prev = PD_n_age10/PD_N_age10*100000) %>% 
  arrange(desc(prev))
  #arrange(country)

meta.output = meta::metaprop(event = PD_n_age10, 
                         n = PD_N_age10, 
                         studlab = study, 
                         pscale=100000, 
                         data = results_pd_age10, 
                         subgroup=agegroup, 
                         common=FALSE,
                         random=TRUE,  
                         subgroup.name = "Age group")

summary(meta.output)

png("age10_pd_prev_plot.png", width = 30, height = 38, units = "cm", res=500)

forest(meta.output, digits=0, digits.se=0)

dev.off()

```

#### Parkinsonism by age group

```{r}
results_pnism_age10 = data10 %>% 
  select(-starts_with("PD")) %>% 
  drop_na() %>% 
  mutate(prev = pnism_n_age10/pnism_N_age10*100000) %>% 
  arrange(desc(prev))
  #arrange(country)

meta.output = meta::metaprop(event = pnism_n_age10, 
                         n = pnism_N_age10, 
                         studlab = study, 
                         pscale=100000, 
                         data = results_pnism_age10, 
                         subgroup=agegroup, 
                         common=FALSE,
                         random=TRUE,  
                         subgroup.name = "Age group")

summary(meta.output)

png("age10_pnism_prev_plot.png", width = 30, height = 30, units = "cm", res=500)

forest(meta.output, digits=0, digits.se=0)

dev.off()

```

